apiVersion: mutations.gatekeeper.sh/v1
kind: ModifySet
metadata:
  name: add-default-image-pull-secrets
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  location: "spec.imagePullSecrets"
  match:
    excludedNamespaces:
    - kube-system
    - kube-node-lease
    - kube-public
    - calico-system
    - external-secrets
    - gatekeeper-system
    - calico-apiserver
    - tigera-operator
  parameters:
    operation: merge
    values:
      fromList:
        - name: global-regcred